server:
  port: 8848

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://dev-api.wuan.in:3306/wuanlife?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: wuanlife
          password: TrKLePXEjwThnABF
#        doufu:
#          url: jdbc:mysql://149.129.55.95:3306/new?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: new
#          password: mDzhNSFKBzaz4KkW


mybatis-plus:
#  mapper-locations: classpath*:org/wuancake/base/*/mapper/mapping/*.xml    #配置mybatis扫描mapper文件xml的路径
#  typeAliasesPackage: org.wuancake.base.*.entit #配置实体类路径
#  configuration:
#    #mybatis-plus配置控制台打印完整带参数SQL语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted


#数据库下划线分割命名方式与驼峰方式相护转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true

